name: copilot
channels:
- https://repo.anaconda.com/pkgs/main
- https://repo.anaconda.com/pkgs/r
dependencies:
- python=3.13
- ipykernel
- conda-forge::nodejs
- conda-forge::sqlite
- pip
- pip:
  - annotated-types==0.7.0
  - anyio==4.9.0
  - boto3==1.38.17
  - botocore==1.38.17
  - certifi==2025.4.26
  - click==8.1.7
  - contourpy==1.3.2
  - cycler==0.12.1
  - dataclasses-json==0.5.7
  - distro==1.9.0
  - dotenv==0.9.9
  - fonttools==4.57.0
  - h11==0.16.0
  - httpcore==1.0.9
  - httpx==0.28.1
  - idna==3.10
  - intervaltree==3.1.0
  - jiter==0.9.0
  - jmespath==1.0.1
  - kiwisolver==1.4.8
  - libcst==1.8.0
  - marshmallow==3.26.1
  - marshmallow-enum==1.5.1
  - matplotlib==3.10.3
  - mypy_extensions==1.1.0
  - networkx==3.4.2
  - numpy==2.2.5
  - openai==1.78.1
  - packaging==25.0
  - pandas==2.3.0
  - pillow==11.2.1
  - pipdeptree==2.26.1
  - psutil==7.0.0
  - pydantic==2.11.4
  - pydantic_core==2.33.2
  - Pygments==2.19.1
  - pyparsing==3.2.3
  - pyre-check==0.9.23
  - pyre-extensions==0.0.32
  - python-dotenv==1.1.0
  - pytz==2025.2
  - PyYAML-ft==7.0.1
  - s3transfer==0.12.0
  - scipy==1.15.3
  - setuptools==78.1.1
  - sniffio==1.3.1
  - sortedcontainers==2.4.0
  - tabulate==0.9.0
  - TestSlide==2.7.1
  - toml==0.10.2
  - tomli==2.2.1
  - tqdm==4.67.1
  - typeguard==2.13.3
  - typing-inspect==0.9.0
  - typing-inspection==0.4.0
  - typing_extensions==4.14.0
  - tzdata==2025.2
  - urllib3==2.4.0
  - wheel==0.45.1
